### ISSUE TITLE
Can't change node features using Network.set_options()

### ISSUE THREAD

**Issue by ronyarmon** [WestHealth/pyvis#141]
I'm trying to use set_options to change nodes size and font size following the instructions in [visJS docs](https://visjs.github.io/vis-network/docs/network/nodes.html)
Plotting the graph with default options:

`import networkx as nx
from pyvis import network as net 
nx_graph = nx.cycle_graph(10)
nt = net.Network(notebook=True)
nt.from_nx(nx_graph)
nt.show('nx.html')`

I'm getting:

![Screenshot from 2022-04-28 12-11-34](https://user-images.githubusercontent.com/30949452/165719474-a61da702-10c3-44cb-84c8-e67b2c792d9d.png)

However when modifying the options: 
`nt = net.Network(notebook=True)
nt.from_nx(nx_graph)
nt.set_options('''
var options = {
    "nodes": {
    "size": 20,
    "shape": "triangle",
    "width":15,
    "font.size":"2"
      },
      "edges":{
        "width":5,
        "font.size":"20"
      }
}
''')
nt.show('nx.html')`
I'm getting a graph with modified edges but no change in nodes size and font.size and no change in edges font.size: 
![Screenshot from 2022-04-28 12-14-48](https://user-images.githubusercontent.com/30949452/165719942-54680557-c526-4c7f-8a42-56aeeae08241.png)
Can you please explain what am I missing? I need to reduce the node size and label font size to accommodate a graph of 4000 nodes which I currently produce but the result is too dense

**Comment by MazrimT** [comment]
Having the exact same issue and can't find any info about how this "string" is supposed to be formatted, tried many different ways now... specifically I'm interested in the layout options.

**Comment by MazrimT** [comment]
actually figured it out... though it's not a documented feature...

you can seemingly access all this way instead:
```
nt = net.Network
# for @ronyarmon 's issue
nt.options.nodes.size = 20
nt.options.nodes.shape = "triangle"
# or for the layout stuff:
nt.options.layout.hierarchical.endabled = True
```

**Comment by ronyarmon** [comment]
Thanks @MazrimT who suggested the following: 
`nt = net.Network
nt.options.nodes.size = 20
nt.options.nodes.shape = "triangle"`

I tried but got: 
`AttributeError: 'Network' object has no attribute 'Options'`

**Comment by MazrimT** [comment]
now that I try it specifically node size doesn't work. 
Also most things doesn't work in 0.2.0 that's installable through pip, but when I install the 0.2.1 from the tar-file here in git it works.

**Comment by jhunpingco** [comment]
I updated the Pypi for 0.2.1 so hopefully this issue has gone away for you.
